I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in script
    show mansion_bg with shake
  File "game/script.rpy", line 55, in <module>
    show mansion_bg with shake
NameError: name 'shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 55, in script
    show mansion_bg with shake
  File "C:\Users\eliza\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 1359, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\eliza\Downloads\renpy-8.2.0-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\eliza\Downloads\renpy-8.2.0-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 55, in <module>
    show mansion_bg with shake
NameError: name 'shake' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
Echoes of the Haunted Manor 1.0
Tue Feb 13 21:35:13 2024
